// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"minieccomerce/configs"
)

// Injectors from wire.go:

func InitializeAuthController() AuthController {
	db := configs.InitDB()
	authRepository := NewAuthRepository(db)
	authService := NewAuthService(db, authRepository)
	authController := NewAuthController(authService)
	return authController
}
